<a href="https://colab.research.google.com/github/nickolas-eisenbarth/Freshman-notebook/blob/main/lectures/Lecture29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recap:

* Classes

# Today's Agenda:

* Numpy




# NumPy
This is a good segue into NumPy. Python provides only a handful of numeric types: ints, longs, floats, and complex numbers. We just declared a class that implements rational numbers. NumPy implements one very useful numeric type: multidimensional arrays. (Remember how difficult it is to handle 2D array in C++)

In [ ]:
import numpy as np

In [ ]:
?np.array

In [ ]:
print([1,2,3,4])

[1, 2, 3, 4]


In [ ]:
print([[0, 2], [1, 5]])

[[0, 2], [1, 5]]


In [ ]:
x = np.array([[0, 2], [1, 5]])
print(type(x))
x

<class 'numpy.ndarray'>


array([[0, 2],
       [1, 5]])

In [ ]:
y = np.array([[4, 0], [0, 4]])
y

array([[4, 0],
       [0, 4]])

In [ ]:
# element-wise addition
x + y

array([[4, 2],
       [1, 9]])

In [ ]:
x

array([[0, 2],
       [1, 5]])

In [ ]:
# element-wise square
x**2

array([[ 0,  4],
       [ 1, 25]])

In [ ]:
x

array([[0, 2],
       [1, 5]])

In [ ]:
y

array([[4, 0],
       [0, 4]])

In [ ]:
# Elementarywise multiplication
x * y

array([[ 0,  0],
       [ 0, 20]])

In [ ]:
x

array([[0, 2],
       [1, 5]])

In [ ]:
y

array([[4, 0],
       [0, 4]])

In [ ]:
 # Matrix multiplication after Python 3.5, traditional way: np.matmul()
x @ y

array([[ 0,  8],
       [ 4, 20]])

In [ ]:
x @ x

array([[ 2, 10],
       [ 5, 27]])

In [ ]:
np.matmul(x, y)# same as x @ y

array([[ 0,  8],
       [ 4, 20]])

In [ ]:
?np.sum

In [ ]:
x

array([[0, 2],
       [1, 5]])

In [ ]:
np.sum(x)  # More about this later

np.int64(8)

# 0. Why Numpy

1. numpy optimize operation for numeric data
2. processes the tasks parallelly.
3. The NumPy package integrates C, C++ in Python. These programming languages have very little execution time compared to Python.

[Jupyter's magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html)

In [ ]:
import time

In [ ]:
a = time.time()
print(a)
b = time.time()
print(b)
print(b-a)

1775227749.8434348
1775227749.843585
0.00015020370483398438


In [ ]:
a = time.time() #t0

for i in range(100000000):
    b = time.time() #t34092>t34091>...>t1
    if b-a > 0.01: #if t2-t0
      break
    pass


print(i)
# measures how many iterations can be performed in 0.01 seconds.

34092


In [ ]:
%%timeit
# This is a magic command available in IPython environments like Jupyter Notebook.
# It automatically measures the execution time of the entire cell.
# It runs the code multiple times to compute an average execution time for better accuracy.
x = list(np.random.rand(10000))
y = list(np.random.rand(10000))
z = 0
for i in range(10000):
    z += x[i] * y[i]

2.85 ms ± 80.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
%%timeit
x = np.random.rand(10000)
y = np.random.rand(10000)
z = x @ y

193 µs ± 25.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
